### ISSUE TITLE
Add support for cargo workspaces

### ISSUE THREAD

**Issue by stanislav-tkach** [deadlinks/cargo-deadlinks#9]
I'm trying `cargo-deadlinks` on our [project](https://github.com/exonum/exonum) and encountering this error. More details:
```
$ RUST_BACKTRACE=1 cargo deadlinks
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:92
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: cargo_deadlinks::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  13: __libc_start_main
  14: _start
```

**Comment by hobofan** [comment]
@DarkEld3r Thanks for the report, I'll see what I can find!

**Comment by DarkEld3r** [comment]
@hobofan I suppose it is because our project is uses workspace, `cargo deadlinks --dir target/doc` works fine.

**Comment by hobofan** [comment]
Oh yeah, workspaces didn't exist when the crate was last updated. But since there are quite a few projects using workspaces now this crate should definitely support them.

**Comment by BenjaminGill-Metaswitch** [comment]
It looks like the problem is https://github.com/deadlinks/cargo-deadlinks/blob/master/src/main.rs#L84. I'd recommend using https://crates.io/crates/cargo_metadata instead of trying to parse the manifest - that should give you workspace support for free.

**Comment by BenjaminGill-Metaswitch** [comment]
Good point (though I think Rust 1.21 makes `cargo doc` work fine with workspaces [it implicitly adds `--all`])
